"""init

Revision ID: 1f41d8140243
Revises: 
Create Date: 2019-02-28 10:59:22.033649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f41d8140243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equality_year')
    op.drop_table('years')
    op.add_column('equality_monitoring', sa.Column('year_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equality_monitoring', 'year_id')
    op.create_table('years',
    sa.Column('year_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('year_id')
    )
    op.create_table('equality_year',
    sa.Column('year_id', sa.INTEGER(), nullable=False),
    sa.Column('equality_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['equality_id'], ['equality_monitoring.equality_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['years.year_id'], ),
    sa.PrimaryKeyConstraint('year_id', 'equality_id')
    )
    # ### end Alembic commands ###
