"""delete students2

Revision ID: 30ed22284c0f
Revises: 58ebf9a86f95
Create Date: 2019-02-28 12:48:03.497001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ed22284c0f'
down_revision = '58ebf9a86f95'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filledIn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signDate', sa.DateTime(), nullable=True))
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.Boolean(), nullable=True))
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.Boolean(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('students2')
    #with op.batch_alter_table('students', schema=None) as batch_op:
    #    batch_op.create_foreign_key(None, 'staff', ['id_staff'], ['id_staff'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('students2',
    sa.Column('id_student', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=30), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('token', sa.VARCHAR(length=60), nullable=True),
    sa.Column('nin', sa.VARCHAR(length=6), nullable=False),
    sa.Column('date_birth', sa.DATETIME(), nullable=False),
    sa.Column('phone', sa.INTEGER(), nullable=False),
    sa.Column('address_1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address_2', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), nullable=False),
    sa.Column('post_code', sa.VARCHAR(length=7), nullable=False),
    sa.Column('year_entry', sa.DATETIME(), nullable=False),
    sa.Column('qualification_image_link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address_proof_image_link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('degree_id', sa.INTEGER(), nullable=True),
    sa.Column('id_staff', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.degree_id'], ),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id_staff'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    # ### end Alembic commands ###
