"""adding id_Staff fk to students

Revision ID: 58ebf9a86f95
Revises: 72f6b545fb03
Create Date: 2019-02-28 12:09:49.237018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ebf9a86f95'
down_revision = '72f6b545fb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_staff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff', ['id_staff'], ['id_staff'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_staff')

    # ### end Alembic commands ###
