"""year entry

Revision ID: 64a54d346268
Revises: 6832335648fe
Create Date: 2019-04-02 09:53:29.154350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a54d346268'
down_revision = '6832335648fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    op.drop_table('student_module')
    op.drop_table('degree_module')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('year_entry',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree_module',
    sa.Column('degree_id', sa.INTEGER(), nullable=False),
    sa.Column('module_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.degree_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('degree_id', 'module_id')
    )
    op.create_table('student_module',
    sa.Column('id_student', sa.INTEGER(), nullable=False),
    sa.Column('module_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('id_student', 'module_id')
    )
    op.create_table('modules',
    sa.Column('module_id', sa.INTEGER(), nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    # ### end Alembic commands ###
