"""SignaturesImageLinks

Revision ID: 71f91c421ddb
Revises: d16cc621347d
Create Date: 2019-04-04 18:32:20.374396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f91c421ddb'
down_revision = 'd16cc621347d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_image_link', sa.String(length=100), nullable=True))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_image_link', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('signature_image_link')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_column('signature_image_link')

    # ### end Alembic commands ###
