"""adding second students

Revision ID: 72f6b545fb03
Revises: 8cef2462a243
Create Date: 2019-02-28 11:59:19.927464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f6b545fb03'
down_revision = '8cef2462a243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students2',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('nin', sa.String(length=6), nullable=False),
    sa.Column('date_birth', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('address_1', sa.String(length=40), nullable=False),
    sa.Column('address_2', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('post_code', sa.String(length=7), nullable=False),
    sa.Column('year_entry', sa.DateTime(), nullable=False),
    sa.Column('qualification_image_link', sa.String(length=100), nullable=True),
    sa.Column('address_proof_image_link', sa.String(length=100), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.Column('id_staff', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.degree_id'], ),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id_staff'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students2')
    # ### end Alembic commands ###
