"""adding Data Confirm

Revision ID: 9a98411827a7
Revises: e011d1b9ab6f
Create Date: 2019-03-07 21:31:49.944584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a98411827a7'
down_revision = 'e011d1b9ab6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataConfirm', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dataConfirm')

    # ### end Alembic commands ###
