"""change verifyTable

Revision ID: a6fa3a7c007c
Revises: 71f91c421ddb
Create Date: 2019-04-05 13:12:48.690723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fa3a7c007c'
down_revision = '71f91c421ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verify', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=True))
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.create_foreign_key(None, 'students', ['userID'], ['id_student'])
        #batch_op.drop_column('id_student')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verify', schema=None) as batch_op:
        pass
        #batch_op.add_column(sa.Column('id_student', sa.INTEGER(), nullable=True))
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.create_foreign_key(None, 'students', ['id_student'], ['id_student'])
        #batch_op.drop_column('userID')

    # ### end Alembic commands ###
