"""Change verifyTable name

Revision ID: 03fed00b25f9
Revises: 2fa6042e2c4d
Create Date: 2019-04-05 13:05:51.054745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fed00b25f9'
down_revision = '2fa6042e2c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('verifyString', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verifyString')
    )
    op.add_column('achievements', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'students', ['userID'], ['id_student'])
    op.drop_column('achievements', 'id_student')
    op.add_column('employer', sa.Column('signature_image_link', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('signature_image_link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'signature_image_link')
    op.drop_column('employer', 'signature_image_link')
    op.add_column('achievements', sa.Column('id_student', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'students', ['id_student'], ['id_student'])
    op.drop_column('achievements', 'userID')
    op.drop_table('verify')
    # ### end Alembic commands ###
