"""empty message

Revision ID: 2fa6042e2c4d
Revises: 
Create Date: 2019-04-02 09:50:06.737367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa6042e2c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree',
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('degree_name', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('degree_id')
    )
    op.create_table('equality_monitoring',
    sa.Column('equality_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('ethnic_group', sa.Integer(), nullable=False),
    sa.Column('religion_group', sa.Integer(), nullable=False),
    sa.Column('transgender', sa.Integer(), nullable=False),
    sa.Column('sexual_orientation', sa.Integer(), nullable=False),
    sa.Column('care_experience', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('disability', sa.Integer(), nullable=False),
    sa.Column('illness_asperger', sa.Boolean(), nullable=False),
    sa.Column('illness_blind', sa.Boolean(), nullable=False),
    sa.Column('illness_deaf', sa.Boolean(), nullable=False),
    sa.Column('illness_long', sa.Boolean(), nullable=False),
    sa.Column('illness_mental', sa.Boolean(), nullable=False),
    sa.Column('illness_learning', sa.Boolean(), nullable=False),
    sa.Column('illness_mobility', sa.Boolean(), nullable=False),
    sa.Column('illness_not_listed', sa.Boolean(), nullable=False),
    sa.Column('illness_not_to_say', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('equality_id')
    )
    op.create_table('staff',
    sa.Column('id_staff', sa.Integer(), nullable=False),
    sa.Column('staff_email', sa.String(length=120), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_staff'),
    sa.UniqueConstraint('staff_email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('students',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('nin', sa.String(length=6), nullable=False),
    sa.Column('date_birth', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('address_1', sa.String(length=40), nullable=False),
    sa.Column('address_2', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('post_code', sa.String(length=7), nullable=False),
    sa.Column('year_entry', sa.Integer(), nullable=False),
    sa.Column('qualification_image_link', sa.String(length=100), nullable=True),
    sa.Column('address_proof_image_link', sa.String(length=100), nullable=True),
    sa.Column('signature_image_link', sa.String(length=100), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.Column('id_staff', sa.Integer(), nullable=True),
    sa.Column('signDate', sa.DateTime(), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.Column('dataConfirm', sa.Boolean(), nullable=False),
    sa.Column('filledIn', sa.Boolean(), nullable=True),
    sa.Column('employmentStartDate', sa.DateTime(), nullable=True),
    sa.Column('jobTitle', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.degree_id'], ),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id_staff'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apprenticeship_evaluation',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('overall_exp', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('q_1', sa.Integer(), nullable=False),
    sa.Column('c_1', sa.String(), nullable=False),
    sa.Column('q_2', sa.Integer(), nullable=False),
    sa.Column('c_2', sa.String(), nullable=False),
    sa.Column('q_3', sa.Integer(), nullable=False),
    sa.Column('c_3', sa.String(), nullable=False),
    sa.Column('q_4', sa.Integer(), nullable=False),
    sa.Column('c_4', sa.String(), nullable=False),
    sa.Column('q_5', sa.Integer(), nullable=False),
    sa.Column('c_5', sa.String(), nullable=False),
    sa.Column('q_6', sa.Integer(), nullable=False),
    sa.Column('c_6', sa.String(), nullable=False),
    sa.Column('q_7', sa.Integer(), nullable=False),
    sa.Column('c_7', sa.String(), nullable=False),
    sa.Column('q_8', sa.Integer(), nullable=False),
    sa.Column('c_8', sa.String(), nullable=False),
    sa.Column('q_9', sa.Integer(), nullable=False),
    sa.Column('c_9', sa.String(), nullable=False),
    sa.Column('q_10', sa.Integer(), nullable=False),
    sa.Column('c_10', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('employer',
    sa.Column('id_employer', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('employer_email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('address_1', sa.String(length=40), nullable=False),
    sa.Column('address_2', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('post_code', sa.String(length=7), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('id_employer')
    )
    op.create_table('progress_report',
    sa.Column('progress_report_id', sa.Integer(), nullable=False),
    sa.Column('id_staff_writer', sa.Integer(), nullable=True),
    sa.Column('id_employer_writer', sa.Integer(), nullable=True),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('question_1', sa.String(), nullable=False),
    sa.Column('question_2', sa.String(), nullable=False),
    sa.Column('question_3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_employer_writer'], ['employer.id_employer'], ),
    sa.ForeignKeyConstraint(['id_staff_writer'], ['staff.id_staff'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('progress_report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress_report')
    op.drop_table('employer')
    op.drop_table('apprenticeship_evaluation')
    op.drop_table('achievements')
    op.drop_table('students')
    op.drop_table('staff')
    op.drop_table('equality_monitoring')
    op.drop_table('degree')
    # ### end Alembic commands ###
